"""ASR subsystem — public facade over :mod:`server.asr.service`.

The service module keeps all Whisper/VAD/speaker internals; this package
re-exports them under stable public names so other projects can depend on
``server.asr`` without touching ``_private`` helpers::

    from server.asr import transcribe, warmup, is_ready, pick_backend
"""

from server.asr.service import (  # noqa: F401
    ASR_BACKEND,
    ASR_COMPUTE,
    ASR_CPU_THREADS,
    ASR_DEVICE,
    ASR_FINAL_BEAM,
    ASR_INITIAL_PROMPT,
    ASR_LANG,
    ASR_MAX_DUP,
    ASR_MODEL,
    ASR_NO_REPEAT_NGRAM,
    ASR_PARTIAL_MIN_GAP,
    ASR_PARTIAL_MIN_NEW,
    ASR_SPECULATIVE,
    ASR_SPECULATIVE_MS,
    ASR_SR,
    MIN_UTT_MS,
    SERVER_PRE_ROLL_S,
    SILERO_HOLD_THRESH,
    SILERO_ON_MS,
    SILERO_ON_THRESH,
    SILERO_SILENCE_MIN_MS,
    SILERO_SILENCE_MS,
    SPEAKER_SIM_MIN,
    STOP_GRACE_S,
    VAD_BACKEND,
    _asr_ready as is_ready,
    _collapse_repeats as collapse_repeats,
    _get_asr as get_asr,
    _get_silero as get_silero,
    _get_speaker_ref as get_speaker_ref,
    _pick_asr_backend as pick_backend,
    _pick_vad_mode as pick_vad_mode,
    _speaker_similarity as speaker_similarity,
    _warmup_asr as warmup,
    _whisper_text as transcribe,
)

__all__ = [
    "ASR_BACKEND",
    "ASR_COMPUTE",
    "ASR_CPU_THREADS",
    "ASR_DEVICE",
    "ASR_FINAL_BEAM",
    "ASR_INITIAL_PROMPT",
    "ASR_LANG",
    "ASR_MAX_DUP",
    "ASR_MODEL",
    "ASR_NO_REPEAT_NGRAM",
    "ASR_PARTIAL_MIN_GAP",
    "ASR_PARTIAL_MIN_NEW",
    "ASR_SPECULATIVE",
    "ASR_SPECULATIVE_MS",
    "ASR_SR",
    "MIN_UTT_MS",
    "SERVER_PRE_ROLL_S",
    "SILERO_HOLD_THRESH",
    "SILERO_ON_MS",
    "SILERO_ON_THRESH",
    "SILERO_SILENCE_MIN_MS",
    "SILERO_SILENCE_MS",
    "SPEAKER_SIM_MIN",
    "STOP_GRACE_S",
    "VAD_BACKEND",
    "collapse_repeats",
    "get_asr",
    "get_silero",
    "get_speaker_ref",
    "is_ready",
    "pick_backend",
    "pick_vad_mode",
    "speaker_similarity",
    "transcribe",
    "warmup",
]
